Fix wls_deployment updates when version is none.
This resoles the following error message When VersionIdentifier is null:

TypeError: cannot concatenate 'str' and 'NoneType' objects